### ISSUE TITLE
Link to website is broken

### ISSUE THREAD

**Issue by twm** [jordansissel/keynav#28]
The link in the readme &mdash; http://www.semicomplete.com/projects/keynav &mdash; is now a 404.

**Comment by eyalev** [comment]
@jordansissel

**Comment by eyalev** [comment]
In the meantime:

http://web.archive.org/web/20180411213516/http://www.semicomplete.com/projects/keynav

**Comment by jordansissel** [comment]
Thank you for reporting, I"ll fix this now. <3

**Comment by jordansissel** [comment]
Done!
