### ISSUE TITLE
How can I store pointer location and click back on?

### ISSUE THREAD

**Issue by ahmedmohiduet** [jordansissel/keynav#34]
In vim I could record some actions via 'qa' which means some keysequences would store at register 'a' and I can replay it later via "@a". Can I store pointer location and and click back later on in some sort of ways like vim we do record & play?

**Comment by sim590** [comment]
@ahmedmohiduet: There's the `record` command (mapped to `q`). Look at the documentation. Then, you can replay with `replay` command. I have never tried it personally though.

**Comment by ahmedmohiduet** [comment]
Thanks very much sim590! :heart: :heart: :heart:

**Comment by ahmedmohiduet** [comment]
Deer @sim590,

I have `record` and `replay` working, also running out of keys. Can we use alias?

**Comment by sim590** [comment]
> Deer @sim590,
> 
> I have `record` and `replay` working, also running out of keys. Can we use alias?

That I can't say. Sorry.
