### ISSUE TITLE
activate keynav with cursorzoom mode by default

### ISSUE THREAD

**Issue by leonardodalinky** [jordansissel/keynav#70]
Hi there!
I wonder if there's a way to activate the keynav with `cursorzoom` mode by default?
I have to press the `c` button to switch to `cursorzoom` mode after the activation, but I prefer it as my default "global" mode.
Is this functionality supported now?

**Comment by MuhammedZakir** [comment]
E.g.

1.
```
alt+semicolon start, cursorzoom 300 300
```

2.
```
alt+semicolon start, grid 4x4, cusorzoom 300 300
```

**Comment by leonardodalinky** [comment]
> E.g.
> 
> 
> ```
> alt+semicolon start, cursorzoom 300 300
> ```
> 
> 
> ```
> alt+semicolon start, grid 4x4, cusorzoom 300 300
> ```

THX dude :)
