### ISSUE TITLE
build error on fedora 37

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [jordansissel/keynav#74]
please help me . i want to make it available on copr
Kernel: 6.0.16-300.fc37.x86_64
glib-1:1.2.10-65.fc37.x86_64
libxdo-1:3.20211022.1-1.fc37.x86_64
using xorg but maybe Xinerama ,XSHAPE is missing how can i check

**make** 

`keynav.c:21:10: fatal error: X11/extensions/shape.h: No such file or directory
   21 | #include <X11/extensions/shape.h>

      |          ^~~~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

make: *** [<builtin>: keynav.o] Error 1`

**Comment by kazi-ar-rafi** [comment]
I installed  glib libxdo libXcomposite-devel.x86_64 libXdamage-devel libXrender-devel libXext-devel Xinerama.h  glib-devel glib2-devel

for now problem is 

Package glib-devel-1:1.2.10-65.fc37.x86_64 is already installed.
Package glib2-devel-2.74.1-2.fc37.x86_64 is already installed.

but 
cc -I/usr/X11R6/include -I/usr/local/include   -c -o keynav.o keynav.c
keynav.c:23:10: fatal error: glib.h: No such file or directory
   23 | #include <glib.h>
      |                    ^~~~~~~~
      |          ^~~~~~~~
      |          ^~~~~~~~

**Comment by kazi-ar-rafi** [comment]
what i tried it 
export CPPFLAGS="-I/usr/include/glib-2.0"
now new error 
cc -I/usr/X11R6/include -I/usr/local/include -I/usr/include/glib-2.0  -c -o keynav.o keynav.c
In file included from /usr/include/glib-2.0/glib/galloca.h:34,
                 from /usr/include/glib-2.0/glib.h:32,
                 from keynav.c:23:
/usr/include/glib-2.0/glib/gtypes.h:34:10: fatal error: glibconfig.h: No such file or directory
   34 | #include <glibconfig.h>



lets try 



export CPPFLAGS="-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include"


still same error 



cc -I/usr/X11R6/include -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -c -o keynav.o keynav.c
In file included from /usr/include/glib-2.0/glib/galloca.h:34,
                 from /usr/include/glib-2.0/glib.h:32,
                 from keynav.c:23:
/usr/include/glib-2.0/glib/gtypes.h:34:10: fatal error: glibconfig.h: No such file or directory
   34 | #include <glibconfig.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: keynav.o] Error 1

**Comment by View-my-Git-Lab-krafi** [comment]
sudo dnf install /*\Xlib -y

  sudo dnf install /*\glib -y

  sudo dnf install /*\glib2 -y

  sudo dnf install /*\glib.h -y

  sudo dnf install /*\cairo-xlib.h -y 

  sudo dnf install /*\xdo.h -y 

sudo dnf install /*\Xrandr.h -y

sudo dnf install /*\Xinerama.h -y

**it may work with only bash**

**Comment by View-my-Git-Lab-krafi** [comment]
and than do a 
`make`
`sudo make install ` 
i will requst to add this instruction on git page
